### ISSUE TITLE
Duplicate Main Menu > Tools > Web Analyzer and Solution Explorer > Context Menu > Run Web Analyzer Items

### ISSUE THREAD

**Issue by cihanuygun** [madskristensen/WebAnalyzer#35] opened 2016-05-25 20:52 UTC
After updating extension to 1.7 menu items are duplicate as below;

![web-analyzer-2](https://cloud.githubusercontent.com/assets/5497248/15555889/85c9bc5c-22d3-11e6-9cb5-dce235025844.jpg)
![web analyzer-1](https://cloud.githubusercontent.com/assets/5497248/15555890/85d1b4de-22d3-11e6-85ac-a29ece651578.jpg)

I have re-installed the extension but, it didnt solve my issue. All of the menu items works proper and all of them distinct but Web Analyzer.

**Comment by madskristensen** [comment] 2016-05-26 16:39
Dupe of #31 
Fix by uninstalling this extension. It is now built in to VS

**Closed as completed by madskristensen** 2016-05-26 16:39 UTC

**Comment by cihanuygun** [comment] 2016-05-26 18:06
Thanks for information.
