### ISSUE TITLE
Multiple Web Analyser menu items in right click menu

### ISSUE THREAD

**Issue by ivi-hamiti** [madskristensen/WebAnalyzer#41] opened 2016-07-14 07:24 UTC
Web analyser context menu items are added multiple times, Using Visual Studio 2015.3

![image](https://cloud.githubusercontent.com/assets/5105883/16831320/a29dcd6c-49a4-11e6-8e7a-8ceaf1be0943.png)

**Comment by RJCuthbertson** [comment] 2016-07-14 18:12
I just came to report this issue too. They're also duplicated in the Tools menu.

![web analyzer tools context items duplicated](https://cloud.githubusercontent.com/assets/11775687/16850412/009dee4c-49cd-11e6-8adc-8cce0362fb29.png)

**Comment by Ciget** [comment] 2016-07-18 14:48
Guys, have the same stuff.

**Comment by tjohnson1010** [comment] 2016-07-21 16:27
Ditto

**Comment by andyrooger** [comment] 2016-08-02 12:42
In case people are getting to this because they're looking only for open issues like I did - this looks like it may be a dupe of #40 #39 #38 #36 #35 #32 #31

**Comment by maxisam** [comment] 2016-08-23 19:37
uninstall it. It is built-in now in new tool preview update.

**Comment by tjohnson1010** [comment] 2016-08-23 20:42
The issue with the Tool Preview Update, is that you can only run it on one file at a time.  With Web Analyser,  I have the option to run it on a solution, project or folder.
FYI: This same feature used to be part of Web Essentials, and I loved how they had an option to include a full scan at build time too.  This saved our team so much time by ensuring no bugs were released, because I could (through options) abort the compile if any warnings/errors were found.  But Web Essentials dropped support for this a while back in favor of this plug-in.

**Comment by JiriZidek** [comment] 2016-11-02 22:56
+1

**Comment by ivi-hamiti** [comment] 2016-11-03 13:26
+1

Msc. Eng. _Ivi Hamiti_
Team Leader, Senior Software Developer
[image: Mobile] +355 (0) 69 24 51 095 [image: Email]
ivi.hamiti@outlook.com [image:
Skype] ivi.hamiti
_Address:_
Rruga Pjeter Budi No. 56
Tirana, 01001
Albania

ivi.hamiti@datalyticslab.com Datalytics LabOrs Group Gmbh
www.orsgroup.de
www.datalyticslab.com

**Comment by streamtree** [comment] 2016-11-22 18:50
+1

**Comment by iappwebdev** [comment] 2016-12-17 13:52
Any update on this?

**Comment by madskristensen** [comment] 2016-12-17 17:41
Uninstall Web Analyzer. It's now built in and that's why it doubles

**Closed as completed by madskristensen** 2016-12-17 17:41 UTC
