### ISSUE TITLE
Duplicate Web Analyzer Menu and options

### ISSUE THREAD

**Issue by rspaulino** [madskristensen/WebAnalyzer#36] opened 2016-06-10 11:25 UTC
<img width="1033" alt="screen shot 2016-06-10 at 7 12 45 am" src="https://cloud.githubusercontent.com/assets/378671/15962932/69021460-2edc-11e6-8fb7-6a34263832f2.png">
<img width="654" alt="screen shot 2016-06-10 at 7 13 11 am" src="https://cloud.githubusercontent.com/assets/378671/15962933/69078cb0-2edc-11e6-8f1d-8dcd57f4461d.png">

**Comment by madskristensen** [comment] 2016-06-10 14:35
Dupe of #31 and #35

**Closed as completed by madskristensen** 2016-06-10 14:35 UTC
